### ISSUE TITLE
Cannot read property 'BaseApi'

### ISSUE THREAD

**Issue by amwinsauto** [7eggs/node-tesseract#4]
I am trying to install this in a cloud-based Node Env. and am getting the following error.  Any ideas?

[ERROR] Cannot find module. "tesseract". Error: Cannot find module '../build/Debug/tesseract_bindings'
[ERROR] Error occurred. TypeError: Cannot read property 'BaseApi' of undefined
    at /app.js:12:25
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by estliberitas** [comment]
@amwinsauto Node version?

**Comment by amwinsauto** [comment]
0.10.22

**Comment by estliberitas** [comment]
> Error: Cannot find module '../build/Debug/tesseract_bindings'

This means native add-on was not compiled. You need tesseract library and devel files installed in order to compile native add-on.

**Comment by estliberitas** [comment]
@amwinsauto Hi, have you fixed your issue? Or any other problems?

**Comment by amwinsauto** [comment]
No.  I already had the dependencies installed - not sure what I am missing.

**Comment by estliberitas** [comment]
@amwinsauto do you have `npm-debug.log` file in the same directory where `node_modules/` exists with `node-tesseract`?
