### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by SPlatten** [7eggs/node-tesseract#6]
I have an iMAC, running macOS Sierra version 10.12.4
node.js version 7.10.0

When I try to install the mode as per the instructions on:

https://www.npmjs.com/package/tesseract

npm install tesseract

I get:

Simons-iMac:docfire simonplatten$ npm install tesseract

> tesseract@0.0.3 install /docfire/node_modules/tesseract
> node-gyp rebuild

  CXX(target) Release/obj.target/tesseract_bindings/src/tesseract_bindings.o
../src/tesseract_bindings.cc:7:9: warning: 'BUILDING_NODE_EXTENSION' macro redefined [-Wmacro-redefined]
#define BUILDING_NODE_EXTENSION
        ^
<command line>:8:9: note: previous definition is here
#define BUILDING_NODE_EXTENSION 1
        ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:17:30: error: expected class name
class BaseApi : public node::ObjectWrap {
                             ^
../src/tesseract_baseapi.h:25:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:26:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Init(const Arguments& args);
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:27:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> SetImage(const Arguments& args);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:28:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Recognize(const Arguments& args);
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:29:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> GetText(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:30:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> GetBoxes(const Arguments& args);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:31:45: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> SetRectangle(const Arguments& args);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:32:45: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> MeanTextConf(const Arguments& args);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:33:44: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> SetVariable(const Arguments& args);
                                           ^~~~~~~~~
                                           v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:34:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> WhitelistCharacters(const Arguments& args);
                                                   ^~~~~~~~~
                                                   v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:35:47: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> SetPageSegMode(const Arguments& args);
                                              ^~~~~~~~~
                                              v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:36:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Clear(const Arguments& args);
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:9:
../src/tesseract_baseapi.h:37:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> End(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:10:
../src/leptonica_pix.h:21:30: error: expected class name
class PixWrap : public node::ObjectWrap {
                             ^
../src/leptonica_pix.h:31:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static PIX* PixRead(const Arguments& args);
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:10:
../src/leptonica_pix.h:32:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:10:
../src/leptonica_pix.h:33:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> GetPath(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/tesseract_bindings.cc:10:
../src/leptonica_pix.h:34:39: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Reload(const Arguments& args);
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/simonplatten/.node-gyp/7.10.0/include/node/v8.h:150:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
1 warning and 19 errors generated.
make: *** [Release/obj.target/tesseract_bindings/src/tesseract_bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /docfire/node_modules/tesseract
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN haraka_local@0.0.1 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "tesseract"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! tesseract@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tesseract@0.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tesseract package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tesseract
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tesseract
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/simonplatten/.npm/_logs/2017-05-06T17_17_33_352Z-debug.log

**Comment by estliberitas** [comment]
The library is quite old, to say. There were a lot of changes in the underlying V8 APIs. So in order to make it work, there is a need to update it to use `nan` bindings.

**Comment by SPlatten** [comment]
Thanks for the response, I've switched to node-tesseract and this is working.
